es:
  es_url: "http://3.37.142.218:9200/"
  username: "elastic"
  password: "bottlestick"
  main_index: "products"
  fail_index: "products_fail_data"

slack:
  url: "https://hooks.slack.com/services/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"
  channel: "#crawling-kihay"

kihay:
  url: "https://m.kihya.com/goods/goods_list.php?cateCd=010"

logpath:
  ec2: "/home/ec2-user/bottle-talk/crawling-logs"
  local: "C:/himedia/logs"

driverpach:
  ec2: "/usr/local/bin/chromedriver"
  local: "C:/Users/tiq00/.wdm/drivers/chromedriver/win64/chromedriver-win64/chromedriver.exe"

